name: Terraform AWS Automation

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'Bucket Name'
        required: true
        type: string
      html_object_key:
        description: 'HTML Object Key'
        required: true
        type: string
      html_base64:
        description: 'HTML File Content (base64)'
        required: true
        type: string

env:
  AWS_REGION: us-west-1
  TF_VAR_bucket_name: ${{ github.event.inputs.bucket_name }}
  TF_VAR_html_object_key: ${{ github.event.inputs.html_object_key }}
  TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY }}
  TF_VAR_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
  HTML_BASE64: ${{ github.event.inputs.html_base64 }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rebuild HTML file from base64
        run: |
          mkdir -p /tmp/html-upload
          echo "$HTML_BASE64" | base64 -d > /tmp/html-upload/index.html
          echo "TF_VAR_html_file_path=/tmp/html-upload/index.html" >> $GITHUB_ENV
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5
      
      - name: Terraform Init
        working-directory: ./infra
        run: terraform init
      
      - name: Terraform Validate
        working-directory: ./infra
        run: terraform validate
      
      - name: Terraform Plan
        working-directory: ./infra
        run: terraform plan
      
      - name: Terraform Apply
        working-directory: ./infra
        run: terraform apply -auto-approve
